<?php

namespace AppBundle\Repository;

/**
 * BicicletaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BicicletaRepository extends \Doctrine\ORM\EntityRepository
{
}
