user:
    resource: "@UserBundle/Resources/config/routing.yml"

app.index:
    resource: "@AppBundle/Controller/IndexController.php"
    type: annotation

app.product:
    resource: "@AppBundle/Controller/ProductoController.php"
    type: annotation
    prefix: /indice

app.bicicletas:
    resource: "@AppBundle/Controller/BicicletaController.php"
    type: annotation
    prefix: /bicicletas
